name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        # So that at least the app is built on all major OSes
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -v -race -timeout=120s -parallel=10 ./...

      - name: Run linters
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v6
        with:
          version: latest

      - name: Build binary
        run: go build
